DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS shelf;

CREATE TABLE user (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  username TEXT UNIQUE NOT NULL,
  password TEXT NOT NULL
);

CREATE TABLE shelf (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  userId INTEGER NOT NULL,
  category TEXT NOT NULL,
  FOREIGN KEY (userId) REFERENCES user(id)
);